variables:
  HDF5_VERSION: "2.0.0"

build-deps-image:
  image: docker:latest
  parallel:
    matrix:
      - OS_IMAGE: ["quay.io/pypa/manylinux_2_34_x86_64"]
        OS_TAG_SLUG: ["manylinux_2_34"]
  variables:
    TAG: "$CI_REGISTRY_IMAGE/deps:$OS_TAG_SLUG"
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker pull $TAG || true
    - echo "Building base image for $OS_IMAGE..."
    - docker build
      --cache-from $TAG
      --build-arg BASE_IMAGE=$OS_IMAGE
      --build-arg HDF5_VERSION=$HDF5_VERSION
      -f Dockerfile
      -t $TAG .
    - docker push $TAG
  rules:
    - changes:
        - Dockerfile
        - .gitlab-ci.yml

build-wheels:
  # needs:
  #   - build-deps-image
  image: docker:latest
  variables:
    CIBW_MANYLINUX_X86_64_IMAGE: "$CI_REGISTRY_IMAGE/deps:manylinux_2_34"
    CIBW_BUILD: "cp310-manylinux_x86_64 cp311-manylinux_x86_64 cp312-manylinux_x86_64 cp313-manylinux_x86_64"
    CIBW_ENVIRONMENT: |
      LD_LIBRARY_PATH=/usr/lib64:/usr/lib
      CC=/usr/bin/gcc
      CXX=/usr/bin/g++
      LD=/usr/bin/ld
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - apk add curl && curl -LsSf https://astral.sh/uv/install.sh | sh
    - export PATH="$HOME/.local/bin:$PATH"
    - uvx pip download --no-binary h5py h5py
    - tar xzf h5py-*.tar.gz
    - cd h5py-*/
    - uvx cibuildwheel --output-dir ../wheelhouse
  artifacts:
    paths:
      - wheelhouse/
